---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  vars:
    nginx_reverse_proxy_app: jupyterhub
    nginx_reverse_proxy_app_listen_port: 8000
    service_name: jupyterhub
    service_uid: 978
  roles:
  - base-os
  - podman-systemd
  - jupyterhub-podman-systemd
  - nginx-reverse-proxy