---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  vars:
    sysacct_name: mysql
    sysacct_uid: 967 # change this depending on disposition of existing system accounts
  roles:
  - almalinux-8-base
  - podman-systemd
  - mysql-podman-systemd