---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: true
  vars:
    sysacct_name: rustdesk
    sysacct_uid: 989
  roles:
  - almalinux-8-base
  - podman-systemd
  - rustdesk-podman-systemd